name: hometasks
description: A new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.11.1

dependencies:
  dotted_border: ^3.1.0
  firebase_auth: ^6.4.0
  firebase_core: ^4.7.0
  flutter:
    sdk: flutter
  flutter_svg: ^2.3.0
  google_sign_in: ^7.2.0
  intl: ^0.20.2
  dart_frog: ^1.2.6
  dart_jsonwebtoken: ^3.4.1
  dotenv: ^4.2.0
  firebase_admin_sdk: ^0.5.2
  google_cloud_firestore: ^0.5.1
  uuid: ^4.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/